services:
  mongodb:
    image: mongo:latest
    ports:
      - '27018:27017'
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGODB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME}
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_PORT=27017
      - MONGODB_DEFAULT_USERNAME=${MONGODB_DEFAULT_USERNAME}
      - MONGODB_DEFAULT_ADMIN_EMAIL=${MONGODB_DEFAULT_ADMIN_EMAIL}
      - MONGODB_DEFAULT_ADMIN_EMAIL_PURE=${MONGODB_DEFAULT_ADMIN_EMAIL_PURE}
      - MONGODB_DEFAULT_ADMIN_PASSWORD=${MONGODB_DEFAULT_ADMIN_PASSWORD}
    volumes:
      - ./docker/mongo/db:/data/db
      - ./docker/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    command: [ --auth ]

    networks:
      - crm_trading_network

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6378:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./docker/redis:/data
    networks:
       - crm_trading_network


networks:
  crm_trading_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.19.0.0/16